# Generated by Django 5.2.15 on 2026-07-04 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('trainer_name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('grade', models.CharField(max_length=20)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='certificates/photos/')),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/pdfs/')),
                ('certificate_template', models.CharField(default='default', max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('pending', 'Pending')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50)),
                ('verification_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='verified', max_length=20)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='certificates.certificate')),
            ],
        ),
    ]
