# Generated by Django 5.2.15 on 2026-07-04 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='course_name',
            new_name='course_domain',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='issue_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='student_name',
            new_name='intern_name',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='duration',
            new_name='internship_duration',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='trainer_name',
            new_name='mentor_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='student_email',
        ),
        migrations.AddField(
            model_name='certificate',
            name='company_name',
            field=models.CharField(default='Durion Technologies', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='internship_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='performance_grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 7, 4)),
            preserve_default=False,
        ),
    ]
